# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Build stage
FROM golang:1.23-alpine AS builder

# Install git for module resolution
RUN apk add --no-cache git

WORKDIR /src

# Cache and download modules
COPY go.mod go.sum ./
RUN go mod download

# Copy all sources
COPY . .

# Build the MCP server binary
RUN go build -o /app/mcp-server-splunk cmd/mcp-server-splunk/main.go

# Runtime stage
FROM alpine:latest
# Install CA certificates for HTTPS
RUN apk add --no-cache ca-certificates

# Copy the built binary
COPY --from=builder /app/mcp-server-splunk /app/mcp-server-splunk

# Default to STDIO mode
ENTRYPOINT ["/app/mcp-server-splunk"]